"use client";

import { useState, useCallback, useMemo } from "react";
import { useRouter } from "next/navigation";
import { ChevronLeft, Check, X, Shuffle, ArrowRight, Trophy, RotateCcw, Zap } from "lucide-react";
import { LessonChart, type ChartScenario } from "@/components/elite/LessonChart";

/* ────────────────────────────────────────────
   Banco de Cenários — Treino Livre
   Perguntas aleatórias cobrindo todo o currículo SMC
   ──────────────────────────────────────────── */

interface Scenario {
  id: string;
  category: string;
  title: string;
  context: string;
  options: string[];
  correct: number;
  explanation: string;
  chartType?: ChartScenario;
}

const SCENARIOS: Scenario[] = [
  // ── Estrutura de Mercado ──
  { id: "s1", category: "Estrutura", title: "BOS vs CHoCH", context: "O preço está em tendência de alta. Fez um novo topo, mas na correção quebrou o último fundo. O que aconteceu?", options: ["BOS — continuação da tendência", "CHoCH — possível mudança de tendência", "Nada relevante — fundos quebram o tempo todo", "Preciso ver o volume pra decidir"], correct: 1, explanation: "Quando o preço quebra o último fundo (low) numa tendência de alta, é um CHoCH (Change of Character) — sinal de que a estrutura pode estar mudando de bullish pra bearish. BOS seria a quebra de um topo (high), confirmando continuação." },
  { id: "s2", category: "Estrutura", title: "Tendência no HTF vs LTF", context: "No diário, a tendência é claramente bearish. No 15 minutos, o preço acabou de fazer um BOS bullish. O que isso representa?", options: ["Reversão — o 15min está certo", "Pullback dentro da tendência bearish do diário", "Os dois timeframes se contradizem, não opero", "O diário está atrasado, confio no 15min"], correct: 1, explanation: "Um BOS bullish no 15min dentro de uma tendência bearish no diário é provavelmente um pullback, não uma reversão. O contexto maior (diário) tem mais peso. Esse pullback pode ser a oportunidade de venda que os institucionais estão usando." },
  { id: "s3", category: "Estrutura", title: "Swing structure vs internal", context: "O preço fez um topo em 18.300, corrigiu até 18.150, e agora está subindo. Você vê um BOS internal (de um topo menor em 18.250) mas o swing high em 18.300 ainda não foi quebrado.", options: ["O mercado é bullish — BOS internal confirma", "Bullish apenas no internal, o swing structure ainda é neutro até quebrar 18.300", "Vendo em 18.250 porque não quebrou o swing", "Internal structure não importa"], correct: 1, explanation: "A internal structure mostra o momentum de curto prazo (bullish), mas o swing structure é o que importa pro viés macro. Até o preço quebrar 18.300 (swing high), o mercado não confirmou continuação bullish no swing. Entradas devem considerar ambas." },

  // ── Order Blocks ──
  { id: "s4", category: "Order Blocks", title: "OB respeitado vs mitigado", context: "O preço voltou ao OB bullish que você marcou. Tocou no topo do OB e está rejeitando. Mas ainda não entrou na metade inferior do OB.", options: ["Entrada boa — o OB está sendo respeitado", "Espero o preço entrar mais no OB (pelo menos 50%) pra entrada com melhor RR", "O OB já falhou se não caiu mais", "Compro no topo do OB com stop apertado"], correct: 1, explanation: "Um OB é mais forte quando o preço penetra pelo menos até a metade dele. Entrada no topo do OB dá RR pior e stop mais apertado (fácil de ser varrido). O ideal é esperar o preço entrar em 50%+ do OB pra ter entrada com desconto e stop abaixo do OB inteiro.", chartType: "ob-bounce" },
  { id: "s5", category: "Order Blocks", title: "OB em zona de supply vs demand", context: "Você identificou um OB bearish num gráfico de 1h. Ele está exatamente numa zona de supply do 4h. O preço está subindo em direção a ele.", options: ["Vendo imediatamente — OB + supply é confluência forte", "Espero o preço chegar no OB e mostrar rejeição antes de entrar", "OBs em zonas de supply são invalidados", "Compro porque o preço está subindo"], correct: 1, explanation: "OB + supply zone é confluência forte, mas nunca entre antes do preço chegar na zona e mostrar rejeição (candle de rejeição, sweep). A confluência aumenta a probabilidade, mas a confirmação protege contra falsos sinais.", chartType: "ob-bounce" },
  { id: "s6", category: "Order Blocks", title: "Múltiplos OBs — qual usar?", context: "Após um BOS bullish, você vê 3 possíveis OBs no pullback. OB-A é o mais recente (perto do preço atual), OB-B está na metade, e OB-C está lá embaixo perto do fundo.", options: ["OB-A — o mais próximo é o mais relevante", "OB-C — o mais extremo é o mais forte (mais discount)", "Todos são válidos — coloco ordens em todos", "O OB que tem FVG dentro é o melhor, independente da posição"], correct: 3, explanation: "Nem o mais próximo nem o mais extremo — o melhor OB é o que tem mais confluência (FVG dentro, zone de premium/discount alinhada, nível institucional). Um OB com FVG dentro tem desequilíbrio + posição institucional, que é a combinação mais forte.", chartType: "ob-bounce" },

  // ── FVG ──
  { id: "s7", category: "FVG", title: "FVG consequent encroachment", context: "Um FVG bullish está entre 18.050 e 18.080. O preço voltou e preencheu até 18.065 (exatamente 50% do FVG) e está reagindo. O que significa?", options: ["O FVG falhou — preencheu demais", "Consequent Encroachment — o preço preencheu 50% do FVG, que é o ponto de equilíbrio. Reação aqui é forte sinal bullish", "Precisa preencher 100% pra ser válido", "50% não tem significado em FVG"], correct: 1, explanation: "Consequent Encroachment (CE) é quando o preço preenche exatamente 50% do FVG. É o ponto de equilíbrio do gap. Reação forte nesse nível é um dos sinais mais precisos do SMC — mostra que os institucionais estão defendendo o fair value.", chartType: "fvg-fill" },
  { id: "s8", category: "FVG", title: "FVG invertido", context: "O preço fez um impulso de alta e deixou um FVG bullish. Depois reverteu completamente e fechou abaixo do FVG inteiro. O que acontece com esse FVG?", options: ["Continua válido — pode reagir quando o preço voltar", "Invertido — agora funciona como resistência (supply) em vez de suporte", "Invalidado — apague do gráfico", "Transformou em Order Block"], correct: 1, explanation: "Quando o preço preenche um FVG inteiro e fecha do outro lado, ele se inverte. Um FVG bullish que foi completamente preenchido agora funciona como zona de supply (resistência). O preço pode reagir de volta quando retornar a ele, mas na direção oposta.", chartType: "fvg-fill" },

  // ── Liquidez ──
  { id: "s9", category: "Liquidez", title: "Trendline liquidity", context: "O preço fez uma trendline de alta limpa com 4 toques. Muitos traders de análise técnica estão usando ela como suporte. O que o institucional vê?", options: ["Suporte forte — quanto mais toques, mais forte", "Pool de liquidez — sell stops de todo mundo que comprou no suporte da trendline estão logo abaixo", "Trendlines não funcionam no SMC", "Compro no próximo toque da trendline"], correct: 1, explanation: "Trendlines são liquidez. Cada toque coloca mais stops logo abaixo. O institucional sabe que abaixo daquela trendline existe um pool enorme de sell stops. Quando quiser comprar com volume, vai varrer essa trendline pra pegar a liquidez e depois reverter.", chartType: "liquidity-sweep" },
  { id: "s10", category: "Liquidez", title: "Inducement", context: "O preço fez um fundo menor (internal low) durante um pullback bearish. Compradores entraram nesse nível pensando que é suporte. O preço está se aproximando desse nível novamente.", options: ["Compro — é suporte confirmado com 2 toques", "Inducement — esse fundo menor é isca pra atrair compradores e pegar a liquidez antes de cair mais", "O preço vai fazer double bottom e subir", "Esse nível é irrelevante"], correct: 1, explanation: "Inducement é quando um internal low ou high é criado pra atrair traders na direção errada. No SMC, esses níveis internos são iscas — os institucionais vão varrê-los pra pegar a liquidez (sell stops dos compradores) antes de continuar na direção original.", chartType: "liquidity-sweep" },
  { id: "s11", category: "Liquidez", title: "BSL vs SSL", context: "O mercado está em tendência bearish no 4h. Existe BSL (buy-side liquidity) acima de 18.200 e SSL (sell-side liquidity) abaixo de 17.900. Pra qual lado o institucional vai buscar primeiro?", options: ["BSL acima — pra se posicionar vendido com liquidez", "SSL abaixo — pra continuar a tendência bearish", "Pode ir pra qualquer lado aleatoriamente", "Nenhum — o mercado vai ficar lateralizado"], correct: 0, explanation: "Em tendência bearish, o institucional precisa de liquidez pra vender. A BSL (buy stops acima de 18.200) fornece essa liquidez. O preço sobe até a BSL, varre os buy stops, o institucional vende nesse nível, e o preço cai. Manipulação antes da distribuição.", chartType: "liquidity-sweep" },

  // ── Sessões ──
  { id: "s12", category: "Sessões", title: "Kill Zone de NY", context: "São 10:15 da manhã BRT. NY abriu há 45 minutos. Você viu o Judas Swing, o preço está retornando pra zona de demanda. Em quanto tempo precisa achar entrada?", options: ["Sem pressa — posso entrar até as 16h", "A kill zone de NY é entre 9:30 e 11:30 BRT — tenho cerca de 1h15 ainda", "Já perdi o horário — kill zone é só nos primeiros 15 min", "Kill zone não existe no NQ"], correct: 1, explanation: "A kill zone de NY pra NQ é geralmente entre 9:30 e 11:30 BRT (10:30-12:30 horário do leste). Depois desse período, a volatilidade cai e os setups ficam menos confiáveis. Você ainda tem tempo, mas não demore — as melhores entradas saem nos primeiros 1-2h.", chartType: "session-asia" },
  { id: "s13", category: "Sessões", title: "Overlap Londres-NY", context: "São 9:30 BRT. A sessão de Londres está aberta desde 4h e NY está abrindo agora. O preço está em consolidação há 2 horas.", options: ["Normal — o preço consolida antes de NY", "O overlap Londres-NY (9:30-12:30 BRT) é o período de maior volume — a consolidação provavelmente vai romper agora", "Londres já definiu a direção, não vai mudar", "Consolidação de 2h significa que não vai ter movimento hoje"], correct: 1, explanation: "O overlap entre Londres e NY (9:30-12:30 BRT) é o período de maior volume e volatilidade do dia. É extremamente comum o preço consolidar nas horas antes e romper exatamente no overlap. É aqui que os melhores setups acontecem.", chartType: "session-asia" },

  // ── AMD ──
  { id: "s14", category: "AMD", title: "Fase de acumulação em range", context: "O preço está num range de 30 pontos há 40 minutos na abertura de NY. Sem direção clara. Um trader iniciante está impaciente e quer entrar logo.", options: ["Ele deveria entrar — quanto mais tempo em range, mais provável o breakout", "Paciência — é acumulação. Entrar agora é apostar. Espere a manipulação e entre na distribuição", "Range significa que não vai ter trade hoje", "Compra no topo, vende no fundo do range"], correct: 1, explanation: "Acumulação é a fase mais perigosa pra operar — o preço vai e volta sem direção. Quem entra aqui está apostando. A sequência correta é: espere o range → espere o spike que varre um lado (manipulação) → entre quando o preço reverter (distribuição). Paciência paga.", chartType: "amd-sweep" },
  { id: "s15", category: "AMD", title: "AMD — como saber qual lado vai varrer", context: "O mercado está em acumulação. Equal highs em 18.200 e equal lows em 18.100. Seu viés diário é bullish. Pra qual lado provavelmente vai ser a manipulação?", options: ["Pra cima (varrer os highs) e depois cair", "Pra baixo (varrer os lows) e depois subir", "Pode ser qualquer lado — é imprevisível", "Vai romper dos dois lados"], correct: 1, explanation: "Se o viés é bullish, a manipulação geralmente é bearish — o preço varre os equal lows (pega sell stops), dando liquidez pro institucional comprar, e depois sobe (distribuição bullish). O Judas Swing vai na direção oposta ao viés do dia.", chartType: "judas-swing" },

  // ── Premium & Discount ──
  { id: "s16", category: "Premium/Discount", title: "Operar em equilíbrio?", context: "O preço está exatamente no nível de 50% do último swing (equilíbrio). Não está nem em premium nem em discount. Você vê um setup que parece bom.", options: ["Entro — o setup é bom independente da zona", "Evito — equilíbrio não dá edge. Espero o preço ir pra discount (compra) ou premium (venda)", "Equilíbrio é a melhor zona pra operar", "50% não tem significado no gráfico"], correct: 1, explanation: "Operar no equilíbrio (50%) não dá vantagem estatística. Os institucionais compram em discount (barato) e vendem em premium (caro). No equilíbrio, o RR é neutro. Espere o preço se afastar do 50% na direção que te dá desconto pra entrar.", chartType: "premium-discount" },
  { id: "s17", category: "Premium/Discount", title: "OTE — Optimal Trade Entry", context: "O preço fez um swing high em 18.300 e está corrigindo. Você quer comprar. A retração de Fibonacci 0.618 (sweet spot) está em 18.112 e tem um OB nessa mesma zona.", options: ["Coloco buy limit em 18.112 — OTE + OB é a confluência perfeita", "Compro em 18.200 — não quero esperar tanto", "0.618 é superstição — Fibonacci não funciona", "Espero 0.786 pra ter preço ainda melhor"], correct: 0, explanation: "OTE (Optimal Trade Entry) é a zona entre 0.618 e 0.786 de Fibonacci. Quando coincide com um OB, é a entrada com melhor RR possível. Comprar em 18.200 (50%) desperdiça desconto. 0.786 pode funcionar mas o preço nem sempre chega lá — 0.618 + OB é o sweet spot.", chartType: "premium-discount" },

  // ── Gestão de Trade ──
  { id: "s18", category: "Gestão", title: "Breakeven — quando mover", context: "Você entrou comprado em 18.060 com stop em 18.045 (15pts de risco). O preço está em 18.078 (+18pts, pouco mais de 1R). Já move pro breakeven?", options: ["Sim — qualquer lucro deve ser protegido", "Espero 1.5R (18.082) pra mover pro breakeven e fazer parcial", "Nunca movo pro breakeven — ou bate o alvo ou o stop", "Movo quando sentir que vai reverter"], correct: 1, explanation: "Mover pro breakeven cedo demais (antes de 1R) faz o trade ser stopado por volatilidade normal. A regra: parcial em 1.5R, breakeven no restante. Isso garante lucro e dá espaço pro trade respirar. 'Quando sentir' não é gestão — é emocional.", chartType: "risk-shield" },
  { id: "s19", category: "Gestão", title: "Trade no lucro — cai notícia", context: "Você está comprado no NQ, trade em +2R. Sai uma notícia econômica que faz o mercado picotar com spread alto. O que você faz?", options: ["Fecho tudo imediatamente — notícia é imprevisível", "Já estou em 2R com stop no breakeven — deixo o stop proteger. Se for a favor, bônus", "Aumento a posição na notícia", "Tiro o stop pra dar espaço"], correct: 1, explanation: "Com 2R de lucro e stop no breakeven, você já ganhou. A notícia pode ir a favor e dar 3-4R, ou pode picotar e stopar no breakeven (lucro zero, mas sem perda). Fechar em pânico desperdiça o potencial. NUNCA tire o stop — e nunca aumente posição em notícia.", chartType: "entry-setup" },
  { id: "s20", category: "Gestão", title: "Revenge trading", context: "Você perdeu 2 trades seguidos hoje (-$380 de -$500 máximo). Aparece um setup que visualmente parece bom, mas seu emocional está abalado.", options: ["Opero com lote normal — o setup é bom", "Opero com lote reduzido pra não bater o limite", "Paro por hoje — emocional abalado + perto do limite = receita pra desastre", "Dobro o lote pra recuperar tudo em um trade"], correct: 2, explanation: "A combinação de emocional abalado + perto do limite diário é a receita perfeita pra revenge trading. Mesmo que o setup seja objetivamente bom, seu julgamento está comprometido. Regra do URA: 2 losses consecutivos ou -70% do limite diário = fecha a plataforma. O mercado abre amanhã." },

  // ── SMT Divergence ──
  { id: "s21", category: "SMT", title: "NQ vs ES divergência", context: "O NQ (Nasdaq) fez um novo low, mas o ES (S&P 500) não fez. Os dois ativos são correlacionados. O que isso significa?", options: ["Normal — cada ativo tem seu movimento", "SMT Divergence — o NQ mostrou fraqueza bearish. Se o ES não confirmou o low, o NQ provavelmente vai reverter pra cima", "O ES está atrasado e vai fazer novo low também", "Divergência entre NQ e ES não é relevante"], correct: 1, explanation: "SMT (Smart Money Technique) Divergence: quando ativos correlacionados (NQ/ES, EUR/DXY) divergem, é sinal de manipulação. O NQ fazendo low que o ES não confirma mostra que o low do NQ foi um sweep de liquidez, não um movimento real. Alta probabilidade de reversão bullish.", chartType: "smt-diverge" },

  // ── Psicologia ──
  { id: "s22", category: "Psicologia", title: "FOMO depois de perder entrada", context: "Você marcou uma zona de entrada em 18.050. O preço chegou lá enquanto você estava longe da tela. Agora o preço está em 18.120, subindo forte sem você. O que faz?", options: ["Entro agora — ainda está subindo", "FOMO é o pior conselheiro. O setup era em 18.050, não em 18.120. Espero o próximo setup", "Entro com stop apertado em 18.110", "Aumento o lote pra compensar o atraso"], correct: 1, explanation: "Entrar atrasado destrói o RR. Sua entrada era 18.050 com stop em 18.040 (10pts de risco). Entrar em 18.120 com mesmo stop seria 80pts de risco — 8x pior. FOMO (Fear Of Missing Out) é emocional, não lógico. Sempre haverá outro setup.", chartType: "entry-setup" },
  { id: "s23", category: "Psicologia", title: "Overtrading", context: "Você já fez 3 trades hoje: 2 ganhos (+$300) e 1 perda (-$100). Net: +$200. São 14h e você vê outro setup possível. Deve operar?", options: ["Sim — estou no lucro, posso arriscar", "Questionar: esse setup é A+? Ou estou operando por tédio/ganância? Se não for excepcional, paro no verde", "Sempre opero até acabar o horário", "Com 3 trades, preciso fazer pelo menos mais 2 pra ter dados estatísticos"], correct: 1, explanation: "Overtrading é fazer trades medianos depois de já ter batido a meta. +$200 no dia é resultado. Se o 4º setup não for claramente A+ (todas as confluências alinhadas), é melhor parar no verde. A maioria dos traders devolvem o lucro do dia por overtrading à tarde." },

  // ── Candles ──
  { id: "s24", category: "Candles", title: "Engulfing em zona de demanda", context: "O preço chegou numa zona de demanda (OB bullish) no 15min. O último candle é um bullish engulfing — corpo verde que engoliu completamente o candle vermelho anterior.", options: ["Confirmação forte — entro comprado com stop abaixo do engulfing", "Engulfing é bom, mas espero o próximo candle fechar acima do engulfing pra confirmar", "Engulfing não funciona no SMC", "Vendo porque o preço está em zona baixa"], correct: 0, explanation: "Bullish engulfing em zona de demanda é uma das confirmações mais fortes. O corpo verde engolindo o vermelho mostra que os compradores dominaram completamente os vendedores naquele nível. Stop abaixo do engulfing (que coincide com abaixo do OB). Não precisa esperar mais confirmação.", chartType: "candle-anatomy" },
  { id: "s25", category: "Candles", title: "3 soldiers vs exaustão", context: "O preço subiu com 7 candles verdes consecutivos, cada um menor que o anterior. O momentum está diminuindo. Você está comprado desde o início.", options: ["Mantenho — ainda está subindo", "Sinais de exaustão — candles diminuindo mostram que os compradores estão perdendo força. Considero fechar parcial ou total", "Aumento posição — 7 candles verdes é muito forte", "Espero um candle vermelho pra decidir"], correct: 1, explanation: "Candles consecutivos com corpos diminuindo = exaustão. O volume comprador está secando. Isso geralmente precede uma correção ou reversão. Se você está no lucro, é momento de proteger (parcial, trailing stop). Nunca aumente posição em exaustão.", chartType: "candle-anatomy" },

  // ── Viés Diário ──
  { id: "s26", category: "Viés", title: "Day of week bias", context: "É segunda-feira. O preço caiu forte na sexta-feira. O candle semanal anterior fechou bearish. O que esperar da segunda?", options: ["Segunda continua o momentum de sexta — vendo na abertura", "Segundas frequentemente fazem o oposto de sexta (rebalanceamento semanal). Espero confirmação antes de operar", "Dia da semana não importa", "Sempre compro na segunda e vendo na sexta"], correct: 1, explanation: "Segundas-feiras frequentemente rebalançam o movimento de sexta. Se sexta caiu forte, segunda pode ter um pullback de alta antes de continuar a tendência. Nunca entre na abertura de segunda assumindo continuação — espere a sessão de NY confirmar o viés do dia." },
  { id: "s27", category: "Viés", title: "News day", context: "Hoje tem FOMC (decisão de juros do Fed) às 15h BRT. São 9h da manhã. O que você faz?", options: ["Opero normalmente até às 15h", "Reduzo exposição ou não opero antes do FOMC — a volatilidade pós-notícia é imprevisível e pode varrer qualquer stop", "FOMC não afeta o NQ", "Abro posição grande antes do FOMC pra pegar o movimento"], correct: 1, explanation: "FOMC é o evento de maior impacto no mercado. O preço costuma ficar em range antes e explodir depois com volatilidade extrema (spreads altos, wicks enormes). Muitos traders profissionais NÃO operam no dia de FOMC, ou operam apenas depois que a volatilidade inicial assentar (30-60 min após).", chartType: "risk-shield" },

  // ── Mesas Proprietárias ──
  { id: "s28", category: "Mesas", title: "Drawdown diário vs total", context: "Sua mesa tem regra: 2% drawdown diário e 5% total. Você está em -1.8% no dia e -4.2% total. Aparece um setup A+.", options: ["Opero com lote mínimo — o setup é A+", "NÃO opero. Estou a 0.2% do drawdown diário E a 0.8% do total. Um loss pode acabar com a conta", "Opero normal — se é A+ tem que entrar", "Aumento lote pra recuperar os 4.2% de drawdown"], correct: 1, explanation: "Quando você está perto de AMBOS os limites (diário e total), qualquer operação é suicida. Mesmo um setup A+ pode dar loss — e esse loss pode custar a conta inteira. Regra: se está a menos de 1% de qualquer limite de drawdown, PARA. Preservar a conta é mais importante que qualquer setup." },

  // ── Estrutura (expansão) ──
  { id: "s29", category: "Estrutura", title: "Weak high vs strong high", context: "Você vê dois topos no gráfico. Topo-A foi feito com candle de rejeição forte (pavio longo superior). Topo-B foi feito com um candle bullish fechando perto do high. Qual é mais provável que seja varrido?", options: ["Topo-A — rejeição mostra que vendedores dominaram, preço pode romper", "Topo-B — é um weak high (preço parou sem rejeição), pool de liquidez intacto acima", "Nenhum — topos iguais não importam", "Sempre o mais recente, independente do formato"], correct: 1, explanation: "Strong high = formado com rejeição (pavio) onde vendedores absorveram compradores. Weak high = preço parou sem batalha, deixando buy stops acumulando. Institucionais priorizam varrer weak highs — a liquidez está lá, sem barreira.", chartType: "liquidity-sweep" },
  { id: "s30", category: "Estrutura", title: "MSS — Market Structure Shift", context: "Tendência bearish clara. O preço fez um lower low e está corrigindo. Agora quebrou o último lower high com um candle de impulso de corpo grande. O que esse rompimento representa?", options: ["Pullback normal — a tendência bearish continua", "MSS — Market Structure Shift, possível início de reversão bullish. Precisa de confirmação", "BOS bearish", "Nada — rompimentos de lower high são comuns"], correct: 1, explanation: "MSS é o primeiro sinal de que a estrutura pode estar mudando. Quebrar um lower high com impulso forte (corpo grande, não wick) mostra que compradores entraram com força. Ainda não é reversão confirmada — espere novo higher low + higher high pra confirmar." },
  { id: "s31", category: "Estrutura", title: "BOS com volume baixo", context: "O preço está em tendência bullish e acabou de quebrar o último topo (BOS). Mas você observa que o candle de rompimento tem corpo pequeno e o volume foi abaixo da média. O que isso sugere?", options: ["BOS forte — confirma continuação bullish", "Possível false breakout — BOS sem volume tende a falhar, pode ser varredura de liquidez", "Volume não importa em futures", "Compro agressivo no rompimento"], correct: 1, explanation: "BOS genuíno tem volume expandindo. Rompimento sem volume frequentemente é uma varredura da buy-side liquidity (stops de quem está short). Sem participação institucional, o movimento não sustenta — e você pode ver o preço voltar rápido pra dentro do range." },
  { id: "s32", category: "Estrutura", title: "HTF vs LTF — prioridade", context: "4h: estrutura bearish clara. 15min: acabou de fazer BOS bullish e parece reversão. Onde seu viés deve estar alinhado?", options: ["15min — é mais recente e atual", "Igual peso pros dois — depende de qual é mais forte", "HTF 4h manda — o BOS do 15min é provavelmente pullback dentro da tendência bearish do 4h", "Ignoro HTF e opero LTF"], correct: 2, explanation: "Regra SMC: HTF define o contexto, LTF define o timing. Estrutura no 4h é bearish → seu viés é bearish. BOS bullish no 15min é uma correção. Use o LTF pra achar pontos de entrada short quando a correção terminar, não pra operar comprado contra o HTF." },
  { id: "s33", category: "Estrutura", title: "Liquidity run vs BOS real", context: "O preço está lateral em range. Você vê um candle que rompe o topo do range por poucos pontos e volta pra dentro no mesmo candle ou no próximo. O que aconteceu?", options: ["BOS bullish — compro a continuação", "Liquidity run — varreu buy stops mas não manteve o rompimento, sinal bearish forte", "Indeterminado — espero mais 5 candles", "Irrelevante — preços rompem o tempo todo"], correct: 1, explanation: "Rompimento que não sustenta = varredura de liquidez (liquidity run / sweep). O preço pega os stops acima do range e volta — isso é um sinal institucional forte de reversão. Opere na direção oposta ao rompimento falso com confirmação." },
  { id: "s34", category: "Estrutura", title: "Internal liquidity", context: "Dentro de uma perna de alta grande, o preço fez vários pullbacks criando lower lows internos. O preço está voltando pra esses lower lows internos. O que isso representa?", options: ["Suporte — o preço deve reagir", "Internal liquidity — pool de sell stops de quem comprou nos pullbacks. Provavelmente será varrido", "Nada relevante", "Nova tendência bearish iniciando"], correct: 1, explanation: "Lower lows dentro de uma perna de alta são internal liquidity — onde os compradores colocaram stops logo abaixo. Institucionais varrem essa liquidez antes de continuar a tendência. Espere o sweep ocorrer + reação, não entre a favor do internal low." },
  { id: "s35", category: "Estrutura", title: "Flip zone", context: "Uma zona que era forte resistência foi rompida com força. O preço agora está retornando a ela. O que espera?", options: ["A zona ainda é resistência — preço vai rejeitar", "Flip zone — resistência vira suporte. Espere defesa bullish e entre comprado", "Zonas antigas não funcionam mais", "Vendo porque está caindo"], correct: 1, explanation: "Quando uma zona-chave é rompida com convicção (candle de corpo grande), ela inverte função. Resistência antiga vira suporte (e vice-versa). Retornos a essa zona frequentemente trazem defesa institucional — é um dos setups mais confiáveis do SMC." },
  { id: "s36", category: "Estrutura", title: "Range expansion após acumulação", context: "O preço ficou 3 dias num range de 40 pontos. Hoje abriu e rompeu com 80 pontos de movimento em 1h. O que aconteceu?", options: ["Breakout comum, nada especial", "Range expansion — após acumulação prolongada, o movimento é amplificado (volatilidade acumulada + liquidez)", "Falso rompimento, vai voltar", "Indicador técnico desbalanceado"], correct: 1, explanation: "Ranges prolongados comprimem volatilidade e acumulam liquidez nos dois lados. Quando institucionais finalmente escolhem a direção, o movimento é explosivo. A expansão após acumulação é uma das oportunidades de melhor RR — mas entrar depois do movimento já feito é tarde." },

  // ── Order Blocks (expansão) ──
  { id: "s37", category: "Order Blocks", title: "Breaker Block — o que é?", context: "Um OB bullish falhou: o preço passou por toda a zona e continuou caindo. Agora o preço subiu e voltou pra essa zona. O que ela representa agora?", options: ["Continua OB bullish — talvez funcione desta vez", "Breaker Block — o OB falhado virou resistência. Opere short quando o preço voltar aqui", "Invalidado — ignorar", "Zona neutra"], correct: 1, explanation: "Breaker Block é um OB que foi violado e invertido. OB bullish que falhou vira resistência (Breaker bearish). O institucional que comprou ali foi stopado; agora eles vendem no retorno pra cobrir. Retornos a Breakers são setups fortes na direção oposta ao OB original." },
  { id: "s38", category: "Order Blocks", title: "Mitigation Block", context: "O preço deixou um OB bearish pra trás, fez lower high, mas NÃO voltou a tocar o OB. Depois o preço caiu forte. Quando deveria ter operado?", options: ["Na primeira chance — comprar na subida", "No Mitigation Block — o último candle bullish antes do lower high funciona como OB 'oculto' que frequentemente é testado depois", "Impossível — OB não testado = setup morto", "Só em timeframes maiores"], correct: 1, explanation: "Mitigation Block = candle oposto que forma quando o preço reverte sem tocar o OB original. Ele 'substitui' o OB não testado. Procure Mitigation Blocks quando o preço não mitigar o OB clássico — é uma camada de profundidade no SMC." },
  { id: "s39", category: "Order Blocks", title: "Rejection Block", context: "Um candle tem um pavio superior muito longo (rejeição) marcando um topo. Os pavios NÃO foram preenchidos nos candles seguintes. Como usar essa zona?", options: ["Ignorar — pavios não contam", "Rejection Block — a zona dos pavios funciona como supply. Vendas com confirmação quando o preço retornar ali", "Sempre é suporte", "Só conta se for doji"], correct: 1, explanation: "Rejection Block = zona dos pavios não preenchidos que marcaram uma rejeição forte. Diferente do OB clássico (último candle antes do impulso), o Rejection Block é formado pelo wick em si. É zona de supply/demand institucional genuína — a defesa foi tão forte que os candles seguintes nem testaram os níveis." },
  { id: "s40", category: "Order Blocks", title: "OB não mitigado — quando usar?", context: "Você vê um OB bullish no 4h formado há 3 dias que nunca foi tocado. O preço está agora na zona. Vale entrar?", options: ["Não — OBs velhos não funcionam", "Sim — OB não mitigado guarda ordens institucionais ainda não executadas. Quanto mais fresh, mais forte", "Só com confirmação no 1min", "Sempre vende em OB não mitigado"], correct: 1, explanation: "OB não mitigado é PRIORITÁRIO sobre OBs já testados. Representa ordens institucionais ainda não executadas. O preço tende a retornar pra preencher essas ordens antes de continuar. Sempre priorize OBs fresh (não mitigados) sobre OBs já testados várias vezes." },
  { id: "s41", category: "Order Blocks", title: "OB com FVG interno", context: "Dois OBs candidatos para entrada bullish: OB-X é limpo (só o candle bearish) e OB-Y tem um FVG dentro dele. Qual escolher?", options: ["OB-X — mais simples é melhor", "OB-Y — OB + FVG = confluência dupla, zona institucional muito mais forte", "Tanto faz", "Só o mais recente"], correct: 1, explanation: "OB com FVG interno é confluência máxima: você tem a zona institucional (OB) + desequilíbrio não preenchido (FVG) na mesma região. O preço tende a reagir mais forte aqui. É o setup preferido de traders ICT/SMC avançados — sempre prefira confluência.", chartType: "entry-setup" },
  { id: "s42", category: "Order Blocks", title: "OB em HTF — prioridade", context: "OB no 1h diz comprar em 18.100. OB no 15min diz comprar em 18.150. O preço está em 18.120. Qual respeitar?", options: ["15min — mais próximo do preço atual", "1h — HTF tem mais peso institucional. Espera chegar no 18.100", "Ignoro os dois", "Média dos dois"], correct: 1, explanation: "Regra de ouro: HTF OB sobrepõe LTF OB. O 1h representa uma zona institucional mais significativa. OBs menores no LTF dentro de uma zona HTF são 'sub-zonas'. Se você entrar no 15min OB, pode ser stopado quando o preço for buscar o 1h OB mais profundo." },
  { id: "s43", category: "Order Blocks", title: "OB violado — stop hunt?", context: "Entrou comprado em OB bullish com stop abaixo da zona. O preço tocou o stop por 3 ticks e imediatamente reverteu pra cima forte. O que aconteceu?", options: ["Bad luck — stop muito apertado", "Stop hunt — institucionais varreram o OB pra pegar liquidez antes do movimento real. Stop deveria estar abaixo com buffer", "Mercado manipulado, impossível operar", "Deveria entrar novamente imediatamente"], correct: 1, explanation: "Stop-hunt clássico: o preço varre a base do OB (onde retail coloca stops) pra pegar liquidez, depois reverte. Colocar stop EXATAMENTE na borda do OB é convite. Use buffer de 3-5 ticks ou stop baseado em ATR. Lesson: a zona exata é zona de defesa, mas institucionais testam o limite." },

  // ── FVG (expansão) ──
  { id: "s44", category: "FVG", title: "IFVG — Inverted FVG", context: "Um FVG bullish foi completamente preenchido e o preço fechou bem abaixo dele. Agora o preço está voltando em direção a esse FVG. O que aconteceu com ele?", options: ["Ainda é suporte bullish", "Virou IFVG (Inverted FVG) — agora funciona como resistência. Opere short quando o preço tocar", "Foi apagado do gráfico", "Virou OB automaticamente"], correct: 1, explanation: "IFVG = FVG que foi preenchido e invertido. Como o preço passou por ele e fechou do outro lado, as ordens institucionais na região foram executadas e a zona mudou de natureza. FVG bullish violado → agora é zona bearish (supply)." },
  { id: "s45", category: "FVG", title: "BPR — Balanced Price Range", context: "Você vê um FVG bullish e, logo depois, um FVG bearish na mesma região de preço. As duas zonas se sobrepõem. Como isso se chama?", options: ["Erro de gráfico", "BPR — Balanced Price Range. Zona de dupla imbalance, reação forte esperada", "Cancelam-se mutuamente", "Não tem nome específico"], correct: 1, explanation: "BPR é quando dois FVGs opostos se sobrepõem. Representa uma zona de grande atividade institucional — ordens de compra E venda ficaram não preenchidas na mesma região. Reação forte esperada quando o preço retornar, em qualquer direção, dependendo do contexto HTF." },
  { id: "s46", category: "FVG", title: "FVG nested", context: "Você vê um FVG bullish de 1h. Dentro dele, há um FVG bullish menor do 15min. Qual o conceito?", options: ["FVGs nested (aninhados) — confluência de timeframes, zona de alta probabilidade", "Erro — FVG não pode estar dentro de outro", "Ignoro o menor", "Só o maior importa"], correct: 0, explanation: "FVGs aninhados em múltiplos timeframes são alta confluência. O FVG 1h indica zona institucional relevante; o 15min dentro dele indica ordens recentes na mesma região. Entrada com stop abaixo do FVG 1h e alvo acima dá ótimo RR." },
  { id: "s47", category: "FVG", title: "Níveis do FVG", context: "Um FVG vai de 18.100 (bottom) a 18.180 (top). O preço voltou e parou em 18.140 reagindo. Qual nível é esse?", options: ["Top do FVG", "CE (Consequent Encroachment) = 50% do FVG", "Fora do FVG", "Nível aleatório"], correct: 1, explanation: "50% do FVG é o CE (Consequent Encroachment), o nível mais respeitado dentro do gap. Outros níveis: top (entrada), 50% (CE, reação forte), bottom (mitigação total). Preços reagindo em CE são sinais institucionais de alta qualidade.", chartType: "fvg-fill" },
  { id: "s48", category: "FVG", title: "FVG HTF vs LTF", context: "FVG no diário em 18.000-18.100. FVG no 15min em 18.050-18.070. O preço está em 18.080. Onde você espera reação primária?", options: ["15min FVG, é mais próximo", "Diário FVG, dominância HTF sobre LTF", "Os dois ao mesmo tempo", "Fora dos dois"], correct: 1, explanation: "Sempre priorize FVG de HTF. Diário > 4h > 1h > 15min. O FVG 15min pode funcionar como reação pequena, mas a reação estrutural real será no FVG diário. Se entrar no 15min, saiba que pode ir até o diário antes da reversão real." },
  { id: "s49", category: "FVG", title: "FVG parcialmente preenchido", context: "FVG tinha 40 pontos. O preço entrou 20 pontos (50% = CE) e já reverteu. O FVG ainda é válido pra próxima vez?", options: ["Não — FVG só é válido se não foi tocado", "Sim — FVG preenchido até CE ainda é válido. Mitigação parcial não invalida", "Só se o HTF não foi violado", "Vira um OB automaticamente"], correct: 1, explanation: "Mitigação parcial (até CE, ou até o top/bottom) não invalida o FVG. Só invalida quando preenchido 100% e fechado do outro lado. FVGs podem ser testados múltiplas vezes e continuar funcionando — a zona institucional permanece ativa até saturação total." },

  // ── Liquidez (expansão) ──
  { id: "s50", category: "Liquidez", title: "Old high/Old low", context: "Você vê um high do último mês em 18.400. O preço está em 18.200 subindo. O que esse old high representa?", options: ["Nada — highs antigos perdem força", "Ímã de liquidez — buy stops acumulados por semanas. O preço tende a buscar old highs/lows", "Suporte", "Só conta se tiver sido tocado recentemente"], correct: 1, explanation: "Old highs/lows são pools de liquidez magnéticos. Quanto mais antigos (semanal, mensal), mais buy/sell stops acumulados. Institucionais usam esses níveis como alvo pra grandes movimentos. Sempre marque old highs/lows relevantes no seu gráfico — são objetivos de medium-term." },
  { id: "s51", category: "Liquidez", title: "Relative equal highs", context: "Você vê 3 topos dentro de 5 pontos entre si (não exatamente iguais). O que isso forma?", options: ["Padrão irrelevante", "Relative Equal Highs — pool de liquidez ainda forte. Não precisam ser idênticos", "Só vale se forem matematicamente iguais", "Triângulo descendente"], correct: 1, explanation: "Equal highs/lows não precisam ser exatamente iguais. Topos relativamente próximos (dentro de 0.1-0.2% do preço) formam pool de liquidez válido. Retail coloca stops logo acima desses topos — institucionais sabem e vão caçá-los.", chartType: "liquidity-sweep" },
  { id: "s52", category: "Liquidez", title: "Liquidity void", context: "O preço caiu 150 pontos em 3 candles (movimento muito rápido). Agora está pausando. O que esse movimento deixou?", options: ["Nada relevante", "Liquidity Void / Imbalance — zona sem lutar institucional. Tende a ser preenchida antes de continuar", "Resistência forte", "Ponto de compra imediata"], correct: 1, explanation: "Movimentos muito rápidos criam liquidity voids — regiões onde não houve 'luta' de compradores/vendedores. Essas zonas funcionam como FVGs macro: o mercado tende a preenchê-las antes de seguir. Marque voids e espere retornos pra operar na direção original." },
  { id: "s53", category: "Liquidez", title: "Stopped at BE — retail trap", context: "Você entrou e moveu pro breakeven. O preço tocou exatamente o BE por 1 tick e depois foi pro alvo sem você. O que aconteceu?", options: ["Azar puro", "BE hunt — retail em massa move stop pro BE. Institucionais sabem e varrem antes do movimento real", "Alavancagem errada", "Mercado manipulado"], correct: 1, explanation: "Mover pra BE cria liquidez previsível. Institucionais sabem onde está a massa de stops em breakeven e frequentemente varrem esse nível antes do movimento principal. Considere mover pra BE só após 1.5-2R, ou usar trailing ATR-based em vez de BE fixo." },
  { id: "s54", category: "Liquidez", title: "HTF liquidity first", context: "HTF (4h): buy side liquidity ainda acima. LTF (15min): sell side liquidity abaixo. Pra onde o preço vai primeiro?", options: ["Sempre pro mais próximo", "Pro HTF — a liquidez de timeframes maiores manda. O preço busca primeiro a liquidez do 4h", "Aleatório", "Igual peso"], correct: 1, explanation: "Regra: HTF liquidity trumps LTF liquidity. Se há BSL acima no 4h, o preço tende a ir atrás disso antes de visitar SSL do 15min. Na dúvida, use HTF como alvo principal e LTF como refinamento de entrada." },
  { id: "s55", category: "Liquidez", title: "Session high/low", context: "Londres fez high em 18.250. NY abriu. O high de Londres ainda não foi tocado. Qual é o target provável?", options: ["Ignora — sessão já acabou", "High de Londres funciona como liquidez pra NY. Provável target", "Só old highs importam", "Depende do DXY"], correct: 1, explanation: "High/low de cada sessão são pools de liquidez válidos durante a próxima sessão. London high não varrido = buy stops acumulados pra NY atacar. Sempre marque session highs/lows (Asia, London, NY) — são alvos/pontos de decisão frequentes.", chartType: "session-asia" },
  { id: "s56", category: "Liquidez", title: "Double top — liquidez", context: "Preço fez double top perfeito em 18.300. Retail está vendo resistência. O que o institucional vê?", options: ["Também vê resistência — vendem junto", "Pool de liquidez — double top = cluster enorme de buy stops acima. Provavelmente vai varrer", "Ignoram padrões gráficos", "Só agem no triple top"], correct: 1, explanation: "Padrões gráficos clássicos (double top, H&S, trendlines) são liquidez institucional. Cada vez que um padrão é validado, mais retail coloca stops no lugar 'certo'. Double top = pool enorme de buy stops acima dos dois picos. Institucional vai varrer antes de reverter (ou continuar)." },
  { id: "s57", category: "Liquidez", title: "Running vs building liquidity", context: "Preço lateral há 2h criando vários highs aproximadamente iguais. O que está acontecendo?", options: ["Building liquidity — cada novo high desses adiciona mais buy stops acima, aumentando o ímã institucional", "Running liquidity — preço está fugindo", "Indecisão irrelevante", "Momentum fraco"], correct: 0, explanation: "Building liquidity = formação do pool. Cada equal high adiciona mais stops. O preço está 'carregando' a zona. Quando institucionais decidirem atacar (sweep), o movimento tende a ser explosivo — a liquidez acumulada vira combustível. Paciência: opere o aftermath, não o building." },

  // ── Sessões (expansão) ──
  { id: "s58", category: "Sessões", title: "Asia range manipulation", context: "Ásia fez range apertado 18.200-18.230. Londres abriu e fez spike até 18.250 antes de cair pra 18.150. O que isso é?", options: ["Breakout de Londres", "Manipulação de Londres da liquidez asiática — sweep de Asia high antes do movimento real", "Nada especial", "Compra em Londres, não vende"], correct: 1, explanation: "Padrão clássico: Londres abre, varre um lado do range asiático pra pegar liquidez, e depois reverte na direção oposta. NY geralmente continua o movimento de Londres. Opere na direção do movimento real (pós-sweep), não no spike inicial.", chartType: "session-asia" },
  { id: "s59", category: "Sessões", title: "NY Lunch — 12h às 13h BRT", context: "É 12h30 BRT (horário de lunch em NY). Preço lateralizou, volume caiu, spreads aumentaram. Você tem um setup 'bom'. Opera?", options: ["Sim — setup é setup", "NÃO — lunch em NY é zona morta. Baixo volume = falsos sinais. Espere 13-14h BRT pra retomada", "Aumento lote pra compensar volume baixo", "Só opero no lunch"], correct: 1, explanation: "NY Lunch (12-13h BRT) é a pior janela pra operar. Volume cai drasticamente, spreads expandem, movimentos são erráticos. A maioria dos setups que 'parecem bons' no lunch falham. Espere o Power Hour (14-16h BRT) pra retomada institucional." },
  { id: "s60", category: "Sessões", title: "Power Hour", context: "São 14h-15h BRT. Você vê retomada de volume, candles maiores, movimentos direcionais. Que janela é essa?", options: ["Janela normal", "Power Hour — última janela institucional forte do dia em NY. Movimentos claros, mas cuidado com reversões perto do close", "Janela de baixa volatilidade", "Janela de ajuste de fim de dia"], correct: 1, explanation: "Power Hour (14-16h BRT / 1-3pm NY) é quando institucionais fazem ajustes finais. Movimentos frequentemente claros mas também tendem a reverter perto do close (16h BRT) com rebalanceamento. Opere com alvo definido e cuide para sair antes do close final." },
  { id: "s61", category: "Sessões", title: "Pre-market gap", context: "NY vai abrir em 30min. Preço está 50 pontos acima do fechamento de ontem (gap up). Como isso afeta a sessão?", options: ["Sem impacto", "Gap cria liquidez em ambas direções — tende a ser preenchido parcialmente ou testado. Volatilidade elevada esperada", "Continuação automática", "Sempre fecha o gap no mesmo dia"], correct: 1, explanation: "Gaps pre-market são pools de liquidez e zonas de interesse. Frequentemente são testados ou fechados parcialmente no início da sessão. Gap não preenchido vira alvo pra depois. Volatilidade tende a ser elevada — ajuste position sizing." },
  { id: "s62", category: "Sessões", title: "Sessão overlap — maior volume", context: "Quais horários BRT têm maior volume e volatilidade no NQ?", options: ["00-02h (Asia solo)", "05-08h (Londres solo)", "10h30-12h30 BRT (overlap Londres + NY)", "16-18h (NY close)"], correct: 2, explanation: "Overlap Londres + NY (9-12h horário de NY = 10-13h BRT, dependendo DST) é a janela de maior volume do dia. Liquidez máxima, spreads apertados, movimentos direcionais mais limpos. Muitos traders profissionais operam EXCLUSIVAMENTE nessa janela.", chartType: "session-asia" },
  { id: "s63", category: "Sessões", title: "Ásia direction hint", context: "Ásia fez movimento bearish claro (30 pontos de queda direcional, não em range). O que isso sugere pra Londres/NY?", options: ["Continuação bearish garantida", "Asia direction frequentemente é revertida ou é false direction. Use como indicador contrário — priorize setups bullish em Londres/NY", "Asia não tem informação", "Só compro após Asia bearish"], correct: 1, explanation: "Ásia direcional costuma ser 'bait' — liquidez acumulada num lado pra ser varrida. Quando Ásia anda muito direcional, Londres/NY frequentemente reverte. Use Ásia como sinal: se Ásia bearish, procure sinais bullish em Londres. Não é regra absoluta, mas é tendência estatística forte." },

  // ── AMD / Power of Three ──
  { id: "s64", category: "AMD", title: "Power of Three (PO3)", context: "Você ouve falar de PO3 (Power of Three). É a mesma coisa que AMD?", options: ["Conceitos diferentes sem relação", "Sim — PO3 (Accumulation / Manipulation / Distribution) é o mesmo framework AMD, aplicado a qualquer timeframe", "PO3 é só pra crypto", "AMD é pra day, PO3 é pra swing"], correct: 1, explanation: "PO3 = AMD. É o mesmo conceito: acumulação → manipulação → distribuição. 'Power of Three' é o termo de Michael J. Huddleston (ICT). Aplica-se em qualquer timeframe (5min, diário, semanal, trimestral). O princípio é o mesmo: institucionais acumulam silenciosamente, manipulam pra pegar liquidez, e distribuem na direção real." },
  { id: "s65", category: "AMD", title: "Daily PO3", context: "No candle diário, você vê: open em cima do high do dia (wick alto), depois preço caiu forte fechando perto do low. Que PO3 é esse?", options: ["PO3 bullish", "Daily PO3 bearish clássico — open varreu buy stops (manipulação up), depois preço caiu (distribuição down)", "Candle aleatório", "Indecisão"], correct: 1, explanation: "Daily candle lê-se como PO3: open e primeiros movimentos = acumulação/manipulação, body = distribuição. Se abriu perto do high e fechou perto do low = bearish PO3 (manipulação up, distribuição down). Sempre leia o daily antes de operar intraday — você vai saber a 'história' do dia.", chartType: "amd-sweep" },
  { id: "s66", category: "AMD", title: "Weekly PO3", context: "Segunda e terça: preço lateralizando (acumulação). Quarta: sweep de low da semana. Quinta-sexta: rally forte. Que estrutura é essa?", options: ["Semana aleatória", "Weekly PO3 bullish — Seg/Ter acumula, Qua manipula, Qui/Sex distribui", "Só vale em crypto", "Sem significado estrutural"], correct: 1, explanation: "Weekly PO3 é poderoso: institucionais operam em ciclos semanais. Segunda/Terça = acumulação. Meio de semana = sweep de liquidez. Quinta/Sexta = movimento real. Use pra posicionar viés semanal. Atenção: não é regra rígida, mas padrão estatístico muito comum." },
  { id: "s67", category: "AMD", title: "AMD timeframe shift", context: "Você identifica AMD no 15min. Entrou na reversão. Mas o HTF (4h) ainda está em fase de acumulação. Risco?", options: ["Nenhum risco", "Sim — AMD do 15min pode estar dentro da acumulação do 4h. Seu 'movimento real' no LTF pode ser só manipulação no HTF", "HTF não importa", "LTF sempre manda"], correct: 1, explanation: "Padrões fractais: AMD em um timeframe pode ser uma fase de AMD maior em timeframe superior. Sua 'distribuição' no 15min pode ser a 'manipulação' do 4h. Sempre alinhe ambos — quando o HTF e LTF estão em fases compatíveis, o trade tem alta probabilidade.", chartType: "amd-sweep" },
  { id: "s68", category: "AMD", title: "Manipulação falsa vs verdadeira", context: "Como distinguir uma manipulação institucional real de um movimento aleatório direcional?", options: ["Impossível distinguir", "Manipulação real: varre nível de liquidez claro (equal lows/highs) + reverte rapidamente com candle forte. Movimento aleatório: rompe e continua sem retorno", "Pela cor do candle", "Por volume apenas"], correct: 1, explanation: "Manipulação real tem 3 características: (1) varre liquidez clara (ponto previsível de stops), (2) reverte no próprio candle ou no seguinte, (3) candle de reversão tem corpo forte. Se falta qualquer um, é apenas movimento direcional — não opere contra a direção." },
  { id: "s69", category: "AMD", title: "Accumulation sem sweep", context: "Preço lateralizou 1h. Acumulou posições laterais. Rompeu pra cima sem varrer nem os lows nem os highs do range. Válido?", options: ["Sim — breakout limpo é melhor", "Não — AMD genuíno EXIGE sweep de liquidez (manipulação). Breakout sem sweep tem alta chance de falhar", "Depende do volume", "Não existe"], correct: 1, explanation: "AMD sem manipulação (sweep) é incompleto. Institucionais precisam de liquidez pra montar posição — sem varrer stops, eles não têm 'contraparte'. Breakouts limpos sem sweep frequentemente são armadilha (false breakout). Espere a manipulação sempre." },

  // ── Premium/Discount (expansão) ──
  { id: "s70", category: "Premium/Discount", title: "OTE sweet spot", context: "Swing high a swing low. Você quer comprar. Quais níveis Fibonacci formam o OTE (Optimal Trade Entry)?", options: ["0.236 a 0.382", "0.50 (equilíbrio)", "0.618 a 0.786 — OTE clássico", "0.886 a 1.0"], correct: 2, explanation: "OTE (Optimal Trade Entry) é a zona entre 0.618 e 0.786 (às vezes 0.705 como sweet spot) do retracement. É onde a confluência premium/discount é mais forte e o RR mais favorável. Entradas fora dessa zona (ex: 0.50) têm RR pior.", chartType: "premium-discount" },
  { id: "s71", category: "Premium/Discount", title: "0.705 vs 0.618", context: "Você pode esperar pullback em 0.618 ou 0.705. Qual dá melhor RR normalmente?", options: ["0.618 sempre", "0.705 — mais profundo, melhor preço, mais desconto. Mas com maior risco de não chegar", "0.50 é melhor que os dois", "0.786 é padrão"], correct: 1, explanation: "0.705 é mais deep que 0.618 = melhor preço = melhor RR, mas com maior risco de o preço não ir tão fundo. 0.618 é mais conservador, entrada mais provável mas com RR pior. Estratégia comum: metade da posição em 0.618, outra metade em 0.705 pra balancear." },
  { id: "s72", category: "Premium/Discount", title: "Deep discount", context: "O preço foi até 0.90 de retracement (90% do swing). Isso ainda é discount ou já virou problema?", options: ["Ainda discount, entrada perfeita", "Muito deep — chegando perto de invalidar a estrutura. Entrada aqui tem RR alto mas probabilidade de funcionar é menor", "Sempre entra em 0.90", "0.90 nem existe em Fibonacci"], correct: 1, explanation: "Retracement além de 0.786 começa a invalidar a tese. Se o preço chega em 0.90, está perto de fechar o swing inteiro — pode ser que o swing original era só manipulação. Entrada aqui é apostando, não seguindo setup. Se está em deep discount, re-avalie o contexto HTF antes de entrar." },
  { id: "s73", category: "Premium/Discount", title: "Premium em downtrend", context: "Tendência bearish. O preço fez pullback até 0.70 de Fibonacci (zona de premium). Que lado operar?", options: ["Compro — preço em premium é zona forte", "Vendo — premium na zona de retracement em tendência bearish = entrada ideal a favor da tendência", "Fico de fora", "Aguardo retracement maior"], correct: 1, explanation: "Em tendência bearish, premium é zona de venda (entrar a favor da tendência com desconto relativo). Em tendência bullish, discount é zona de compra. Use premium/discount pra timing, não pra decidir direção — o direcional vem do HTF." },
  { id: "s74", category: "Premium/Discount", title: "Equilibrium reversal", context: "O preço está EXATAMENTE no 0.50 (equilíbrio). Sinal de compra ou venda?", options: ["Compro — equilíbrio é suporte", "Vendo — equilíbrio é resistência", "Nem um nem outro — no equilíbrio você não tem edge. Espere o preço sair de lá na direção do viés", "Aleatório"], correct: 2, explanation: "Equilíbrio (0.50) é zona neutra — nem premium nem discount. Você não tem edge estatístico. Espere o preço sair do equilíbrio na direção do seu viés HTF, e entre no próximo pullback. Operar exatamente em 0.50 é operar sem vantagem." },

  // ── Gestão de Trade (expansão) ──
  { id: "s75", category: "Gestão", title: "Position sizing — 1% rule", context: "Conta de $10.000. Seu stop está a 50 pontos (NQ = $5/ponto). Qual é o tamanho máximo da posição pra respeitar 1% de risco?", options: ["1 contrato (risco = $250 = 2.5%)", "0.4 micro contratos (risco ~$100 = 1%)", "2 contratos", "Depende do humor"], correct: 1, explanation: "Risco 1% de $10k = $100 max loss. Com stop 50 pontos x $5/pt = $250 por contrato. 0.4 contrato daria $100 (use micro NQ = $0.50/ponto, 4 micros). Sempre calcule position sizing ANTES de entrar. Sem isso, você apenas acha que está gerenciando risco." },
  { id: "s76", category: "Gestão", title: "Correlation risk", context: "Você está comprado no NQ e agora quer comprar o ES também com 1% em cada. Qual o risco total real?", options: ["1% + 1% = 2% somados", "Quase 2% — NQ e ES são altamente correlacionados, se um cair o outro cai junto", "Reduzido — diversifica", "0% — cancela"], correct: 1, explanation: "NQ e ES têm correlação ~0.90. Posições em ambos NÃO diversificam, multiplicam o risco. 1% em NQ + 1% em ES ≈ 1.9% de risco efetivo. Use correlação: escolha UM dos dois (o que tiver melhor setup) em vez de dobrar exposição ao mesmo movimento." },
  { id: "s77", category: "Gestão", title: "Weekly loss limit", context: "Sua regra pessoal: máximo 3% de perda semanal. Você está em -2.8% na quinta-feira. Sexta-feira tem FOMC. Operar?", options: ["Sim — setup é A+, vale tentar", "NÃO — 0.2% até o limite e um dia volátil = suicídio. Fecha a semana, preserva capital mental e financeiro", "Dobrar o lote pra recuperar", "Só em timeframe menor"], correct: 1, explanation: "Limites são limites. Quando está perto, qualquer trade pode virar desastre — especialmente em dia de notícia. Feche a semana no verde relativo (-2.8% é recuperável; -5% é trauma). Capital mental é tão importante quanto capital financeiro." },
  { id: "s78", category: "Gestão", title: "Consecutive losses — quando parar", context: "Você teve 3 losses consecutivos hoje (todos setups aparentemente bons). Que decisão tomar?", options: ["Continuar — variação estatística normal", "Parar e revisar — 3 losses seguidos pode ser o setup mudou de contexto, ou seu read está errado. Revise antes de continuar", "Aumentar lote", "Mudar de estratégia"], correct: 1, explanation: "3 losses consecutivos é sinal de alerta. Pode ser: (a) contexto de mercado mudou (tendência alterada, volatilidade), (b) seu read está errado hoje, (c) estado mental comprometido. Pare, revise os trades objetivamente, só retome se identificar o problema. Muitos traders quebram contas nessa sequência." },
  { id: "s79", category: "Gestão", title: "Scale out strategy", context: "Alvo de 3R. Qual a estratégia de parcial mais comum em gestão ativa?", options: ["Tudo no alvo final", "50% em 1.5R (breakeven no restante), 50% em 3R", "Só 25% no alvo, 75% runner sem stop", "Tudo em 1R"], correct: 1, explanation: "Estratégia padrão: parcial em 1.5R garante lucro e reduz pressão psicológica. BE no restante dá chance de ir além sem risco. 50/50 é o balance comum. Variações: 33/33/33 (três alvos) ou 70/30 (mais agressivo). Escolha baseado em como o mercado está se comportando (trending vs range)." },
  { id: "s80", category: "Gestão", title: "Trailing stop ATR-based", context: "Você está em trade lucrativo. Quer proteger sem matar o trade cedo. Qual trailing usar?", options: ["Fixed 20 pontos", "Breakeven simples", "Trailing baseado em ATR (ex: 2x ATR de 14 períodos) — adapta à volatilidade atual", "Sem trailing"], correct: 2, explanation: "Trailing fixo não considera volatilidade atual. ATR-based ajusta dinamicamente: em alta volatilidade, stop mais largo; em baixa, mais apertado. Exemplo: 2x ATR(14) é padrão. Outra opção: trailing baseado em estrutura (cada novo higher low em bullish trade)." },
  { id: "s81", category: "Gestão", title: "Adding to winners — pyramiding", context: "Seu trade está em +2R. Você quer aumentar a posição pra lucrar mais. Pode?", options: ["Não — nunca aumente em trade aberto", "Sim, mas só com lote menor e stop no BE do trade original. Pyramiding agressivo mata contas", "Sempre com mesmo lote", "Só se dobrar o alvo"], correct: 1, explanation: "Pyramiding (aumentar posição em trade ganhador) pode funcionar, mas com regras estritas: (1) lote adicional menor que original, (2) stop de toda a posição no BE do trade original (garante que o setup todo não vira loss), (3) só em trades claramente trending. Mal feito, transforma trade ganhador em loser." },
  { id: "s82", category: "Gestão", title: "Stop hunt avoidance", context: "Como evitar ser stopado por wicks e manipulações institucionais?", options: ["Stops mais apertados pra menos risco", "Não usar stop (só mental)", "Stop atrás de estrutura significativa (abaixo do OB inteiro, abaixo de swing low, etc) com buffer de 3-5 ticks", "Aleatório"], correct: 2, explanation: "Stop deve estar onde a tese é INVALIDADA — não num nível arbitrário. Se comprou em OB, stop abaixo do OB com buffer (não exato). Se comprou em swing low, stop abaixo do swing. Stops apertados baseados só em $ viram fonte de liquidez institucional." },
  { id: "s83", category: "Gestão", title: "News spike management", context: "Você está em trade quando sai notícia inesperada. Preço pula 30 pontos em 1 segundo e volta. Seu stop foi tocado por 2 pontos. Loss real?", options: ["Sim — stop é stop", "Provavelmente slippage — em eventos de volatilidade extrema, stops executam acima/abaixo do preço marcado. Risco real pode ter sido maior", "Nada aconteceu", "Dobrar a posição"], correct: 1, explanation: "Stops em eventos de notícia sofrem slippage: podem executar MUITO pior que o preço marcado. Seu 'stop a -1R' pode virar -2R ou -3R real. Por isso: reduza exposição ANTES de notícias conhecidas (FOMC, NFP, CPI). Não é só 'o stop me protege' — proteção depende de liquidez, que some em shocks." },
  { id: "s84", category: "Gestão", title: "Breakeven timing", context: "Quando mover pro breakeven faz SENTIDO?", options: ["Imediatamente quando está em +0.5R", "Em 1.5-2R após confirmação de continuação (ex: novo higher high, rompimento de nível chave)", "Nunca", "Quando sentir medo"], correct: 1, explanation: "Mover pra BE cedo demais (0.5-1R) faz você ser stopado por variação normal. Move só depois de (a) mínimo 1.5-2R de lucro E (b) confirmação de que o trade está 'ativo' (nova estrutura a favor). Antes disso, é volatilidade normal — dê espaço pro trade respirar." },

  // ── SMT Divergence (expansão) ──
  { id: "s85", category: "SMT", title: "ES/NQ divergência", context: "NQ acabou de fazer novo low. Você olha o ES no mesmo horário — não fez novo low correspondente. O que isso indica?", options: ["Nada — cada ativo tem seu movimento", "SMT bullish divergence — NQ pode ter feito sweep de liquidez falso. Sinal de reversão potencial", "Divergência bearish", "Ignorar"], correct: 1, explanation: "ES e NQ têm correlação ~0.95. Quando NQ faz novo low mas ES não confirma, é SMT divergence bullish — indica que o new low do NQ foi apenas sweep de liquidez, não movimento real. Use como sinal de reversão, especialmente se coincide com OB/FVG de HTF.", chartType: "smt-diverge" },
  { id: "s86", category: "SMT", title: "NQ/YM divergência", context: "NQ fez higher high forte. YM (Dow) não acompanhou — ficou abaixo do high anterior. O que isso sugere?", options: ["NQ é mais forte, compra", "SMT bearish divergence — NQ pode estar varrendo buy stops enquanto o 'mercado largo' (YM) não confirma. Potencial reversão", "YM é irrelevante", "Compra YM que vai subir"], correct: 1, explanation: "NQ sem confirmação do YM em máximas é divergência clássica. NQ (tech-heavy) pode estar 'correndo' sozinho puxado por poucas ações. Sem confirmação do mercado largo (YM), o movimento é frágil. Sinal de cautela em longs." },
  { id: "s87", category: "SMT", title: "DXY vs EURUSD", context: "DXY subindo forte. EURUSD deveria estar caindo (correlação inversa). Mas EURUSD está lateralizando. O que isso indica?", options: ["Mercado quebrado", "Divergência — EUR está mais forte do que deveria. Possível reversão de DXY chegando", "DXY vai continuar subindo", "Ignorar"], correct: 1, explanation: "DXY e EURUSD têm correlação inversa ~-0.95 (EUR é 57% do DXY). Quando DXY sobe mas EUR não cai, é divergência — EUR está absorvendo a pressão. Frequentemente precede reversão de DXY. Traders de forex usam essa divergência sistematicamente." },
  { id: "s88", category: "SMT", title: "BTC/ETH correlation", context: "BTC caiu 3%. ETH caiu só 0.5%. Eles têm correlação histórica alta. O que ETH mostrando força indica?", options: ["ETH vai cair em seguida — catching up", "Força relativa de ETH — possível outperformance chegando. BTC pode estar perto de bottom, ETH pode liderar próxima alta", "Divergência irrelevante", "Comprar BTC"], correct: 1, explanation: "Crypto correlation: BTC geralmente lidera. Quando ETH não acompanha a queda, é sinal de força relativa — capital institucional pode estar posicionando em ETH. Historicamente, essas divergências precedem outperformance do ativo mais forte. Use pra decidir qual crypto priorizar em longs." },
  { id: "s89", category: "SMT", title: "Gold/Silver ratio", context: "Gold caindo 2%. Silver caindo 0.3%. Que leitura fazer?", options: ["Silver está atrasado, vai cair em seguida", "Silver mostrando força relativa — pode indicar rotação ou bottom próximo dos metais", "Gold e Silver não têm correlação", "Sell gold, sell silver"], correct: 1, explanation: "Silver tende a seguir Gold com beta maior. Quando Silver não acompanha queda, sinal de absorção — demanda industrial + especulativa pode estar suportando. Historicamente, divergência positiva em Silver precede bottom em metais preciosos." },
  { id: "s90", category: "SMT", title: "SMT + estrutura", context: "Você identifica SMT divergence bullish em NQ/ES no 15min. Mas o HTF 4h ainda está em tendência bearish forte. Entrar long?", options: ["Sim — SMT é sinal forte", "Cauteloso — SMT pode ser válido pra scalp, mas contra tendência HTF é operar contra a maré. Se entrar, use tamanho reduzido e stop apertado", "Aumentar lote — divergência múltipla é garantia", "Ignorar SMT"], correct: 1, explanation: "SMT é sinal relativo, não absoluto. Contra HTF forte, SMT pode funcionar pra scalps de 1-2R mas dificilmente pra runners. Regra: use SMT a favor do HTF pra trades maiores; contra HTF, scalp pequeno com gestão rígida." },

  // ── Psicologia (expansão) ──
  { id: "s91", category: "Psicologia", title: "Confirmation bias", context: "Você está comprado. Notícia ruim sai. Você procura no Twitter justificativas pra segurar a posição e ignora análises bearish. Que viés é esse?", options: ["Pensamento positivo", "Confirmation bias — você está filtrando informação que confirma sua posição e ignorando sinais opostos", "Análise completa", "Disciplina"], correct: 1, explanation: "Confirmation bias é procurar só informação que confirma o que você já pensa. Em trading, isso trava saídas: em vez de re-avaliar objetivamente, você vira cego pros sinais contrários. Cure com: pergunte SEMPRE 'o que faria eu sair deste trade?' antes de entrar. Se aparecer, execute sem negociar." },
  { id: "s92", category: "Psicologia", title: "Sunk cost fallacy", context: "Você está em trade com -1.5R (stop virtual original era -1R). Pensa: 'já perdi tanto, não vou sair agora, vai voltar'. Erro?", options: ["Não — faz sentido esperar", "SIM — sunk cost fallacy. O que você já perdeu é irrecuperável mentalmente. Decisão deve ser: este trade faz sentido AGORA? Se não, sair", "Depende do valor", "Aumentar posição"], correct: 1, explanation: "Sunk cost fallacy: achar que o que já perdeu 'conta' pra manter a posição. O passado é irrecuperável. A decisão deve ser: 'se eu não tivesse este trade, eu o abriria AGORA neste ponto?' Se a resposta é não, feche. Pensar em 'recuperar' o que perdeu é como reforçar um buraco." },
  { id: "s93", category: "Psicologia", title: "Loss aversion", context: "Você realiza lucro em +1R rápido mas segura trades perdedores esperando reversão até -3R. Por quê?", options: ["Estratégia inteligente", "Loss aversion — a dor da perda é psicologicamente ~2x maior que o prazer do ganho. Traders tendem a cristalizar ganhos cedo e segurar perdas por muito tempo", "Gestão de risco", "Normal"], correct: 1, explanation: "Loss aversion (Kahneman) é o viés mais caro do trader. Você fecha ganhos pequenos pra 'garantir' e segura perdas pra 'não virar real'. Resultado: muitos pequenos ganhos + poucas perdas grandes = conta zerada. Cure com: plano escrito de saída (alvo + stop) ANTES de entrar, execução robótica." },
  { id: "s94", category: "Psicologia", title: "Overconfidence após wins", context: "Você teve 5 wins consecutivos. Agora vê um setup 'bom'. Tendência é aumentar o lote?", options: ["Sim — está no flow", "CUIDADO — overconfidence após streak de wins leva a posições mal dimensionadas. A regressão à média é real e vai chegar", "Sempre aumentar em streak", "Independente"], correct: 1, explanation: "Overconfidence é especialmente perigoso APÓS sequências de wins. Você começa a achar que tem 'edge especial' e a dimensionar grande. A regressão à média volta, e você devolve lucros acumulados em 1-2 trades. Regra: mantenha position sizing fixo por estratégia, independentemente de streaks." },
  { id: "s95", category: "Psicologia", title: "Recency bias", context: "Nas últimas 2 semanas, compras em OB estão falhando muito. Você começa a achar 'OBs não funcionam mais'. Verdade?", options: ["Sim — mercado mudou", "Recency bias — 2 semanas não é amostra estatística. Estratégias têm ciclos. Não mude baseado em amostra pequena", "Sempre mudar quando falha", "OBs nunca funcionam"], correct: 1, explanation: "Recency bias faz você dar peso excessivo a eventos recentes. Toda estratégia tem ciclos de hot/cold. 2 semanas não é amostra estatística (você precisa de 50-100 trades). Se OB tem edge histórico, não abandone por 10 trades ruins. Revise execução, não a estratégia." },
  { id: "s96", category: "Psicologia", title: "Anchoring ao preço de entrada", context: "Você comprou em 18.200. Preço está em 18.150. Alvo original era 18.300. Agora você quer sair em 18.220 'assim que voltar'. Erro?", options: ["Não — sair no BE é seguro", "SIM — você anchorou no preço de entrada. A decisão de saída deveria ser baseada no setup atual, não em 'recuperar o que perdeu'", "Depende", "Sempre sair no BE"], correct: 1, explanation: "Anchoring ao preço de entrada distorce saídas. Se o setup ainda é válido, por que sair em BE? Se não é, por que esperar voltar? Decisão de saída deve ser baseada em estrutura/setup atual, não em 'tornar-se inteiro'. Seu preço de entrada é irrelevante pro mercado — é só relevante psicologicamente." },
  { id: "s97", category: "Psicologia", title: "Revenge trade", context: "Perdeu trade há 10 minutos. Vê 'setup' imediato no mesmo ativo. Sente urgência de entrar pra recuperar. Que sinal é esse?", options: ["Oportunidade — entrar agora", "Revenge trade — seu emocional quer 'recuperar' o loss anterior. Setups em estado emocional quase nunca têm edge real. Respire, talvez pule essa", "Normal do trading", "Dobrar lote"], correct: 1, explanation: "Revenge trade é o assassino número 1 de contas. Você está vendo 'setups' que não existem ou dimensionando mal porque precisa recuperar. Regra: após loss, espere mínimo 15-30 min antes do próximo trade. Melhor ainda, se for 2+ losses, pare por hoje. O mercado abre amanhã." },

  // ── Candles (expansão) ──
  { id: "s98", category: "Candles", title: "Pin bar em zona de demanda", context: "Preço chega em OB bullish. Aparece candle com pavio inferior 3x maior que o corpo, corpo pequeno no topo do candle. Como chama e o que indica?", options: ["Pin bar — rejeição forte da zona baixa, sinal de reversão bullish", "Doji normal", "Inside bar", "Nada especial"], correct: 0, explanation: "Pin bar = pavio longo + corpo pequeno. Em zona de demanda, pin bar bullish (pavio inferior) mostra rejeição forte: compradores absorveram vendedores naquele nível. Um dos sinais mais limpos de reversão. Stop abaixo do pavio, entrada no fechamento do pin.", chartType: "candle-anatomy" },
  { id: "s99", category: "Candles", title: "Hammer vs Shooting Star", context: "Pavio longo inferior + corpo pequeno no topo = hammer. Pavio longo superior + corpo pequeno no fundo = ?", options: ["Hammer invertido", "Shooting Star — padrão de reversão bearish no topo de rally", "Doji", "Marubozu"], correct: 1, explanation: "Shooting Star aparece no topo de uma alta: pavio longo superior mostra rejeição — vendedores puxaram o preço de volta. Confirmação: candle seguinte bearish. Em zonas de supply/resistência, é um dos sinais mais claros de reversão de topo." },
  { id: "s100", category: "Candles", title: "Inside bar — consolidação", context: "Candle atual tem high e low DENTRO do range do candle anterior. Que padrão é?", options: ["Engulfing", "Inside bar — indica consolidação/indecisão. Geralmente precede continuação ou rompimento na direção da tendência", "Doji", "Pin bar"], correct: 1, explanation: "Inside bar = candle contido pelo anterior. Indica pausa no momentum. Breakout do high do inside bar em tendência bullish é sinal de continuação; breakout do low em bearish é continuação. Evite operar o inside bar em si — espere o rompimento com confirmação." },
  { id: "s101", category: "Candles", title: "Outside bar (engulfing)", context: "Candle atual tem high MAIOR e low MENOR que o candle anterior. Corpo bullish. Como chama e o que indica?", options: ["Doji", "Inside bar", "Outside bar / Bullish Engulfing — sinal forte de reversão ou continuação bullish, dependendo do contexto", "Pin bar"], correct: 2, explanation: "Outside bar (também chamado engulfing quando o corpo engole o anterior) mostra mudança agressiva de controle. Bullish engulfing em zona de demanda = sinal de reversão forte. Bullish engulfing em tendência bullish = continuação forte. Contexto define interpretação." },
  { id: "s102", category: "Candles", title: "3 candles de exaustão", context: "Tendência bullish. Últimos 3 candles têm corpos cada vez menores, topos quase no mesmo nível. O que isso indica?", options: ["Continuação garantida", "Exaustão — momentum secou. Possível reversão ou consolidação. Se em posição comprada, considere parciais", "Indecisão temporária", "Falta de volume"], correct: 1, explanation: "Corpos decrescentes em topo = exaustão de compradores. Cada novo candle mostra menos convicção. Não é reversão confirmada, mas é alerta: tendência pode estar acabando. Se está comprado, é momento de parciais ou trailing mais apertado — não de adicionar posição." },

  // ── Viés Diário (expansão) ──
  { id: "s103", category: "Viés", title: "Weekly Open", context: "Segunda-feira. Preço abriu em 18.000. Agora é quinta e o preço está em 18.200. Onde está o weekly open?", options: ["Esqueça, não importa", "Em 18.000 — weekly open é referência forte durante a semana, funciona como pivot pra viés", "Só conta se for no fechamento", "No fechamento de sexta"], correct: 1, explanation: "Weekly Open (preço no abertura da segunda) é nível institucional importante. Preço acima do weekly open = viés bullish na semana; abaixo = bearish. Frequentemente o preço retorna ao weekly open antes de continuar. Marque sempre esse nível." },
  { id: "s104", category: "Viés", title: "Monthly Open", context: "É dia 15 do mês. Preço está 200 pontos acima do monthly open. O que isso sugere?", options: ["Irrelevante", "Mês bullish — preço acima do monthly open indica viés institucional de alta. Até o preço voltar abaixo, operar a favor (longs em pullback)", "Sempre vende", "Só conta no trimestre"], correct: 1, explanation: "Monthly Open é nível de HTF. Acima = viés bullish do mês; abaixo = bearish. Em trading intradiário, alinhar com monthly open aumenta probabilidade. Monthly open respeitado por semanas é zona institucional crítica." },
  { id: "s105", category: "Viés", title: "PDH/PDL — Previous Day", context: "Preço está se aproximando do PDH (Previous Day High). O que esperar?", options: ["Nada, high antigo", "PDH é pool de liquidez — buy stops acumulados. Provavelmente vai ser testado/varrido. Use como alvo ou como ponto de decisão", "Suporte", "Ignora"], correct: 1, explanation: "PDH e PDL (Previous Day High/Low) são níveis institucionais diários. Quase sempre são testados no dia seguinte. Retail coloca stops em cima do PDH (shorts) e abaixo do PDL (longs). Institucionais atacam. Marque PDH/PDL no seu gráfico sempre." },
  { id: "s106", category: "Viés", title: "Quarterly theory", context: "Você ouve sobre 'quarterly theory' em trading ICT. Do que se trata?", options: ["Análise de resultados trimestrais", "Conceito ICT que divide o tempo em quartis (ano/mês/semana/dia/hora) e aplica PO3 em cada nível — previsão macro", "Só vale pra ações", "Indicador técnico"], correct: 1, explanation: "Quarterly Theory (ICT): o tempo fractal-mente se divide em 4 partes, cada uma com fase (A/M/D/X). Ano → 4 trimestres, trimestre → 3 meses, mês → 4 semanas, semana → 5 dias, dia → 4 sessões. Aplicar AMD em cada quartil permite ler macro e micro simultaneamente. Conceito avançado mas poderoso." },
  { id: "s107", category: "Viés", title: "Draw on Liquidity (DOL)", context: "Você identifica que há BSL clara em 18.300 (equal highs por 3 dias) e viés HTF bullish. Como esse nível é chamado?", options: ["Resistência", "DOL — Draw on Liquidity. O 'ímã' que o preço está buscando. Alvo institucional provável", "Entrada", "Ignorável"], correct: 1, explanation: "DOL (Draw on Liquidity) é o alvo institucional provável — onde a liquidez está acumulada e onde o preço 'quer' ir. Identificar DOL transforma trading: em vez de adivinhar direção, você lê onde está a liquidez relevante e alinha trades nessa direção." },

  // ── Mesas Proprietárias (expansão) ──
  { id: "s108", category: "Mesas", title: "Payout 80/20 vs 90/10", context: "Mesa A paga 80% de payout ao trader. Mesa B paga 90%. As outras regras são iguais. Qual escolher?", options: ["Sempre a B — mais payout", "Depende: payouts maiores frequentemente vêm com regras mais restritivas. Compare TODAS as regras", "A é sempre melhor", "Payout não importa"], correct: 1, explanation: "Payout é só uma parte. Mesa com 90% pode ter: drawdown mais apertado, payout mínimo alto, prazo pra pegar lucro, regras de consistência. Analise: payout × max drawdown × regras de consistência × frequência de saque. Mesa 'melhor' é aquela onde você sobrevive, não a de maior payout." },
  { id: "s109", category: "Mesas", title: "Trailing drawdown", context: "Sua mesa usa 'trailing drawdown' de $2000. Você abriu conta com $50k. Chegou em $52k. Qual é seu max drawdown agora?", options: ["$48k (50k - 2k)", "$50k (52k - 2k) — o trailing subiu com o balance máximo", "Não mudou", "$46k"], correct: 1, explanation: "Trailing drawdown SOBE com o high water mark (balance máximo atingido). Se você chegou em $52k, seu min allowable é $50k (52k - 2k). Se você cair pra $49.999, a conta vira. Por isso: em mesas com trailing, proteção de lucro acumulado é crítica — cada profit aumenta a restrição." },
  { id: "s110", category: "Mesas", title: "Consistency rule", context: "Mesa exige que nenhum dia represente mais de 30% do lucro total do mês. Você fez $800 num dia e só $100 nos outros 10 dias. Total $1.800. Regra violada?", options: ["Não — é só meta", "SIM — $800 / $1.800 = 44% > 30%. Saque pode ser bloqueado", "Depende do humor", "Regra não existe"], correct: 1, explanation: "Consistency rules existem pra filtrar traders que têm 'dias sortudos'. 30% significa que nenhum dia pode ser dominante demais. Pra sacar, você precisa ter lucros DISTRIBUÍDOS. Solução: se num dia você já tem 25%+ do mensal, pare — senão viola a regra e trava saque." },
  { id: "s111", category: "Mesas", title: "Scaling account size", context: "Você passou no challenge de $50k. Agora tem opção de escalar pra $100k. Pros e contras?", options: ["Sempre escalar — mais lucro", "Sempre ficar pequeno", "Avaliar: $100k dobra lucro mas também dobra pressão psicológica. Se você mal sobreviveu em $50k, $100k pode quebrar. Escale quando conforto mental atingido", "Depende da mesa"], correct: 2, explanation: "Escalonar conta é psicológico. O setup é o mesmo, mas o $/ponto dobra. Traders que lucram confortáveis em $50k às vezes travam em $100k por medo. Regra: só escale quando estiver consistentemente lucrando em $50k por pelo menos 3 meses e sentir que o sizing atual não é desafio." },

  // ── Timing (nova categoria) ──
  { id: "s112", category: "Timing", title: "First 90 minutes", context: "NY abriu. Os primeiros 90 min (9:30-11:00 ET / 10:30-12:00 BRT) são conhecidos como...", options: ["Janela morta", "Kill zone / Opening Range — janela de maior oportunidade institucional do dia", "Pre-market", "Lunch"], correct: 1, explanation: "Os primeiros 90 min de NY são a 'kill zone' principal. Maior volume, volatilidade direcional, setups mais limpos. Institucionais posicionam-se nesse período. Muitos day traders profissionais só operam essa janela — depois é chop ou lunch." },
  { id: "s113", category: "Timing", title: "Silver Bullet — 10-11 ET", context: "ICT fala de 'Silver Bullet' como uma janela temporal específica. Qual?", options: ["8-9 ET", "10-11 ET / 11-12 BRT — janela de alta probabilidade para reversões/continuações em NY", "14-15 ET", "Depende do humor"], correct: 1, explanation: "Silver Bullet (ICT) = 10-11 ET (11-12 BRT dependendo DST). Institucionais fazem movimentos chave nessa janela de 1h. Frequentemente é onde o 'Judas Swing' inicial é revertido e a direção real se revela. Muitos traders usam exclusivamente essa janela." },
  { id: "s114", category: "Timing", title: "Killing Time — afternoon chop", context: "É 13-15h BRT. Você identificou que o mercado está lateral, sem direção clara. Como chama essa zona?", options: ["Power hour", "Killing Time / Afternoon Chop — zona onde institucionais descansam, volatilidade cai, setups ruins", "Kill zone", "Silver bullet"], correct: 1, explanation: "Killing Time (13-15h BRT) geralmente é baixa qualidade pra entradas. Volume cai, spreads expandem, movimentos erráticos. Melhores traders pulam ou operam apenas setups excepcionais. Espere Power Hour (14-16h ET / 15-17h BRT) pra retomada." },
  { id: "s115", category: "Timing", title: "Friday afternoon — position squaring", context: "Sexta-feira 15h BRT. Mercado está ficando errático, tendência invertendo. Explicação provável?", options: ["Dia normal", "Position squaring — traders fechando posições antes do fim de semana. Movimentos contra-tendência podem ocorrer. Evite entrar em novos trades", "Sempre operar forte na sexta", "Irrelevante"], correct: 1, explanation: "Sexta à tarde frequentemente vê reversões por position squaring (ninguém quer carregar posição grande no fim de semana por news risk). Trades contra tendência semanal aumentam. Estratégia: feche lucros de longo, evite novas posições de swing, limite-se a scalps curtos." },
  { id: "s116", category: "Timing", title: "Monday open — gap", context: "Segunda 9:30 ET. NQ abre com gap de 80 pontos acima do fechamento de sexta. Primeira reação?", options: ["Comprar o momentum", "Cauteloso — gaps de segunda frequentemente são preenchidos total ou parcialmente antes da direção real do dia se revelar", "Vender imediatamente", "Ignorar gap"], correct: 1, explanation: "Monday gaps são frequentemente 'testados' — preço volta a tocar o fechamento de sexta antes de continuar. Operar o gap diretamente é arriscado. Estratégia: espere a primeira hora se desenvolver, identifique se o gap vai ser preenchido ou não, e opere a direção pós-teste." },

  // ── Saída (nova categoria) ──
  { id: "s117", category: "Saída", title: "Early exit signals", context: "Trade em +1.5R. Você vê bearish engulfing candle se formando contra sua direção long. Fechar?", options: ["Não — segurar até alvo", "Sinais opostos fortes justificam saída antecipada. +1.5R é lucro, proteger é melhor do que ver virar loss", "Dobrar posição", "Ignorar velas"], correct: 1, explanation: "Setup reverso em trade lucrativo justifica saída antecipada. Regra: sair quando a tese original não é mais válida. Bearish engulfing forte em long de 1.5R significa que a estrutura mudou. Levar 1.5R pra casa é melhor que esperar +3R que pode virar -1R." },
  { id: "s118", category: "Saída", title: "Time-based exit", context: "Você entrou num setup que 'deveria' andar em 30 min. Já faz 1h30 e o preço mal andou (stuck em +0.3R). O que fazer?", options: ["Esperar mais, vai andar", "Sair — 'time stop'. Quando setup não funciona no tempo esperado, a tese provavelmente falhou. Melhor sair flat que esperar virar loss", "Aumentar posição", "Stop no -0.5R"], correct: 1, explanation: "Time stop é uma ferramenta subutilizada. Setups têm 'janela de oportunidade'. Se o preço fica preso por muito tempo, provavelmente a direção projetada não vai acontecer. Sair flat ou com -0.2R preserva capital pra o próximo setup válido." },
  { id: "s119", category: "Saída", title: "Structure-based trailing", context: "Você está em trade bullish trending. Como fazer trailing baseado em estrutura?", options: ["Stop fixo atrás do entry", "A cada novo higher low confirmado, subir stop pra logo abaixo dele — deixa o trade 'respirar' e protege com estrutura", "Sempre BE", "Nunca trailing"], correct: 1, explanation: "Structure trailing é o mais natural: em tendência bullish, stop atrás do último higher low. Quando novo higher low se forma, move stop. Isso deixa o trade correr enquanto estrutura está intacta e automaticamente fecha quando estrutura quebra. Melhor pra trends de médio-longo." },
  { id: "s120", category: "Saída", title: "Final target vs scale out", context: "Alvo final de 3R atingido. Você tem 50% ainda aberto. Fechar?", options: ["Segurar todo — pode ir mais", "Fechar o final no alvo planejado. Planejamento > esperança. Pode deixar runner pequeno (10-15%) se há tendência forte", "Aumentar posição", "Duplicar alvo"], correct: 1, explanation: "Disciplina: se seu plano é 3R, feche em 3R. Alterar alvos em live é invenção. Quer pegar mais? Deixa um runner PEQUENO (10-15% da posição) com stop trailing agressivo. O núcleo (85-90%) foi pro plano. Consistência vem de execução, não de 'acertar grande'." },
  { id: "s121", category: "Saída", title: "Exit on news", context: "Você está em trade ganhador. Sai notícia impactante. Preço picota extremo. O que fazer?", options: ["Segurar — stop protege", "Considerar fechar manualmente — stops em shocks têm slippage ruim. Se o trade já pagou bem, garantir o lucro vale a pena", "Aumentar posição", "Retirar stop"], correct: 1, explanation: "Em shocks de notícia, spreads explodem e stops sofrem slippage pior. Se você já tem lucro decente (+1.5R ou mais) e a volatilidade está errática, fechar manualmente garante. Não retire stop — isso é ainda pior. Se não tem lucro e volatilidade está extrema, considerar fechar também (flat > unknown risk)." },
];

/* ────────────────────────────────────────────
   Shuffle helper
   ──────────────────────────────────────────── */

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** Shuffle a scenario's options and return the new correct index.
 *  Eliminates position bias — student can't memorize "always B". */
function shuffleScenarioOptions(scenario: Scenario): { options: string[]; correct: number } {
  const order = shuffle([0, 1, 2, 3]);
  return {
    options: order.map((i) => scenario.options[i]),
    correct: order.indexOf(scenario.correct),
  };
}

/* ────────────────────────────────────────────
   Treino Livre — Modo Infinito
   ──────────────────────────────────────────── */

export default function TreinoLivrePage() {
  const router = useRouter();
  const [queue, setQueue] = useState<Scenario[]>(() => shuffle(SCENARIOS));
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [answered, setAnswered] = useState(false);
  const [stats, setStats] = useState({ correct: 0, total: 0 });
  const [sessionDone, setSessionDone] = useState(false);

  const scenario = queue[currentIdx];

  // Shuffle options per question — prevents "always B" bias.
  // Re-computes when scenario id changes (not on every render).
  const shuffled = useMemo(() => shuffleScenarioOptions(scenario), [scenario.id]);

  const handleAnswer = (idx: number) => {
    if (answered) return;
    setSelectedAnswer(idx);
    setAnswered(true);
    setStats(prev => ({
      correct: prev.correct + (idx === shuffled.correct ? 1 : 0),
      total: prev.total + 1,
    }));
  };

  const handleNext = () => {
    if (currentIdx >= queue.length - 1) {
      // Reshuffle and restart
      setQueue(shuffle(SCENARIOS));
      setCurrentIdx(0);
    } else {
      setCurrentIdx(prev => prev + 1);
    }
    setSelectedAnswer(null);
    setAnswered(false);
  };

  const handleFinish = () => {
    setSessionDone(true);
  };

  const handleRestart = () => {
    setQueue(shuffle(SCENARIOS));
    setCurrentIdx(0);
    setSelectedAnswer(null);
    setAnswered(false);
    setStats({ correct: 0, total: 0 });
    setSessionDone(false);
  };

  // Session summary
  if (sessionDone) {
    const pct = stats.total > 0 ? Math.round((stats.correct / stats.total) * 100) : 0;
    return (
      <div className="max-w-2xl mx-auto space-y-8 py-8">
        <button onClick={() => router.push("/elite/pratica")} className="text-[13px] text-white/30 hover:text-white/60 transition-colors flex items-center gap-1">
          <ChevronLeft className="w-3.5 h-3.5" /> Voltar
        </button>

        <div className="relative overflow-hidden rounded-2xl border border-white/[0.06] bg-gradient-to-b from-[#141417] to-[#0e0e10] p-10 text-center">
          <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-brand-500/40 to-transparent" />

          <div className="w-20 h-20 rounded-2xl bg-brand-500/10 mx-auto mb-6 flex items-center justify-center">
            <Trophy className="w-9 h-9 text-brand-500" />
          </div>

          <h2 className="text-[28px] font-bold text-white mb-2">Sessão Encerrada</h2>
          <p className="text-[42px] font-bold text-brand-500 mb-1">{pct}%</p>
          <p className="text-[14px] text-white/40 mb-8">{stats.correct} de {stats.total} decisões corretas</p>

          <div className="flex gap-3 justify-center">
            <button onClick={handleRestart} className="flex items-center gap-2 px-6 py-3 rounded-xl bg-white/[0.04] border border-white/[0.08] text-[13px] text-white/60 font-medium hover:bg-white/[0.06] transition-all">
              <RotateCcw className="w-4 h-4" /> Nova sessão
            </button>
            <button onClick={() => router.push("/elite/pratica")} className="flex items-center gap-2 px-6 py-3 rounded-xl bg-brand-500 text-[13px] font-bold text-white transition-all hover:brightness-110">
              Voltar <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6 py-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button onClick={() => router.push("/elite/pratica")} className="text-[13px] text-white/30 hover:text-white/60 transition-colors flex items-center gap-1">
          <ChevronLeft className="w-3.5 h-3.5" /> Voltar
        </button>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-[12px] text-white/30">Acertos:</span>
            <span className="text-[13px] text-white/70 font-bold font-mono">{stats.correct}/{stats.total}</span>
          </div>
          <button onClick={handleFinish} className="text-[12px] text-white/25 hover:text-white/50 transition-colors">
            Encerrar
          </button>
        </div>
      </div>

      {/* Category badge */}
      <div className="flex items-center gap-3">
        <Shuffle className="w-4 h-4 text-brand-500/50" />
        <span className="text-[11px] text-white/30 uppercase tracking-wider font-semibold">Treino Livre</span>
        <span className="text-[11px] text-white/20">·</span>
        <span className="text-[11px] text-white/25">{scenario.category}</span>
      </div>

      {/* Question */}
      <div className="relative overflow-hidden rounded-2xl border border-white/[0.06] bg-gradient-to-b from-[#141417] to-[#0e0e10] p-7">
        <h3 className="text-[18px] font-bold text-white mb-3">{scenario.title}</h3>
        <p className="text-[13px] text-white/45 leading-relaxed">{scenario.context}</p>
      </div>

      {/* Chart (only when scenario has a chartType) */}
      {scenario.chartType && (
        <LessonChart key={scenario.id} scenario={scenario.chartType} />
      )}

      {/* Options */}
      <div className="space-y-2.5">
        {shuffled.options.map((option, idx) => {
          const isSelected = selectedAnswer === idx;
          const isCorrect = idx === shuffled.correct;
          let borderColor = "border-white/[0.06]";
          let bg = "bg-[#0e0e10]";
          let textColor = "text-white/60";

          if (answered) {
            if (isCorrect) {
              borderColor = "border-green-500/40";
              bg = "bg-green-500/[0.06]";
              textColor = "text-green-400";
            } else if (isSelected && !isCorrect) {
              borderColor = "border-red-500/40";
              bg = "bg-red-500/[0.06]";
              textColor = "text-red-400";
            } else {
              textColor = "text-white/20";
            }
          }

          return (
            <button
              key={idx}
              onClick={() => handleAnswer(idx)}
              disabled={answered}
              className={`w-full text-left px-5 py-4 rounded-xl border ${borderColor} ${bg} ${textColor} transition-all duration-200 ${
                !answered ? "hover:border-white/[0.15] hover:bg-white/[0.02] cursor-pointer" : ""
              }`}
            >
              <div className="flex items-start gap-3">
                <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center flex-shrink-0 mt-0.5 ${
                  answered && isCorrect ? "border-green-500 bg-green-500/20" :
                  answered && isSelected && !isCorrect ? "border-red-500 bg-red-500/20" :
                  isSelected ? "border-white/40" : "border-white/[0.10]"
                }`}>
                  {answered && isCorrect && <Check className="w-3 h-3 text-green-400" />}
                  {answered && isSelected && !isCorrect && <X className="w-3 h-3 text-red-400" />}
                </div>
                <span className="text-[13px] leading-relaxed">{option}</span>
              </div>
            </button>
          );
        })}
      </div>

      {/* Explanation */}
      {answered && (
        <div className="rounded-2xl border border-white/[0.06] bg-[#141417] p-6">
          <p className="text-[12px] text-white/30 uppercase tracking-wider font-semibold mb-2">Explicação</p>
          <p className="text-[13px] text-white/50 leading-relaxed">{scenario.explanation}</p>

          <button onClick={handleNext} className="mt-5 flex items-center gap-2 px-5 py-3 rounded-xl bg-brand-500 text-[13px] font-bold text-white transition-all hover:brightness-110">
            Próxima <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}
    </div>
  );
}
